apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "mychart.fullname" . }}
    labels:
        {{- include "mylib.companyLabels" . | nindent 4 }}
        {{- include "mychart.labels" . | nindent 4 }}
data:
    mykey: {{ .Values.myval | quote }}